### ISSUE TITLE
Add esbuild steps with metafile output to README

### ISSUE THREAD

**Issue by yonta** [exoego/esbuild-bundle-analyzer#27]
I tried this repository and stumbled upon the need to output a metafile in the esbuild configuration.
I think it would be helpful to include this in the README.

**Comment by exoego** [comment]
I think this part in README describes that.
Do you think it is not enough?
<img width="787" alt="image" src="https://github.com/exoego/esbuild-bundle-analyzer/assets/127635/98fab5b5-09b0-4b2a-806c-b507f3fcd735">

**Comment by yonta** [comment]
Oh.
Sorry, I am using esbuild v0.19 (< v0.20), so I skipped this sentence.
I need not to skip, but I didn't notice.

**Comment by yonta** [comment]
For example, how about splitting the usages steps in the README?

1. Configure esbuild to output a metafile.
    - CLI version
    - JS version
1. Write the GitHub Actions.

The CLI version is easier than the JS version, and I've also split the esbuild configuration steps.
What do you think?

**Comment by exoego** [comment]
Added CLI version example, which I was not aware of, to README in https://github.com/exoego/esbuild-bundle-analyzer/pull/29

**Comment by yonta** [comment]
Thanks to update README🙌
