### ISSUE TITLE
Add option to hide 'No change' behind details

### ISSUE THREAD

**Issue by palexcast** [exoego/esbuild-bundle-analyzer#58]
In larger applications the list of files can become large, and no-change is likely less important than those that are changed. 

Would be nice to either always, or have an option for hiding these behind a "details" / accordion.

**Comment by palexcast** [comment]
Btw, really great job with this! I have been looking for a tool like this for a while :)

**Comment by exoego** [comment]
@palexcast 
Thanks.
The proposed feature makes sense to me.
Shipped in https://github.com/exoego/esbuild-bundle-analyzer/releases/tag/v1.4.0
