### ISSUE TITLE
feature-request: Display aggregated percentage of change in bundle size

### ISSUE THREAD

**Issue by Eirmas** [exoego/esbuild-bundle-analyzer#75]
Would it be possible to include a number representing the change in total bundle size from the base branch and compare branch?
The names of the chunks are very subject to change in some projects, so it often just lists "Added" and "Deleted".
What I am more interested in is seeing how much the total bundle size of my application changed with my PRs.

**Comment by exoego** [comment]
> a number representing the change in total bundle size

Let me confirm.

You want to know +19.89KB
which is a sum of +632 B,  -5.38KB, and +24.64KB in the below example?
![image](https://github.com/user-attachments/assets/f32d9559-9ea1-4a68-a038-424606958ac2)

**Comment by Eirmas** [comment]
> > a number representing the change in total bundle size
> 
> Let me confirm.
> 
> You want to know +19.89KB which is a sum of +632 B, -5.38KB, and +24.64KB in the below example? ![image](https://private-user-images.githubusercontent.com/127635/355394549-f32d9559-9ea1-4a68-a038-424606958ac2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Mzc1MTIsIm5iZiI6MTcyMjkzNzIxMiwicGF0aCI6Ii8xMjc2MzUvMzU1Mzk0NTQ5LWYzMmQ5NTU5LTllYTEtNGE2OC1hMDM4LTQyNDYwNjk1OGFjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwOTQwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDhlYWZjMzAyOTJlZTk0ZjZiZmMyOGMwN2QyYWFjYTc2ZWM3NTA2YTcxZTAxN2IyMWJhNGU5ZTJhN2YyNWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HJYxKkS91D9ixM58BO_4rgW9oBIR2nsFNeJRdkPFxtU)

Yes! I think that would be very helpful in larger apps with loads of chunks, and especially when chunks use hash naming and receives a new name after build.

**Comment by Eirmas** [comment]
Maybe including a percentage would be nice too, like in the analysis table
So it would be something like +19.89 KB (+?.?%)
