### ISSUE TITLE
bug: Total shows wrong numbers

### ISSUE THREAD

**Issue by Eirmas** [exoego/esbuild-bundle-analyzer#90]
The total row seems to show the wrong diff percentage

The hidden bundles shows a bunch of "added" / "removed" lines. Could it be related to that?

![image](https://github.com/user-attachments/assets/b99b43c0-39a6-45ff-999f-14b96e3e79a6)

**Comment by Eirmas** [comment]
For context, the PR in the picture did not introduce any changes to the bundle size, so the percentage should have been 0 because baseBundleSize === newBundleSize

**Comment by Eirmas** [comment]
![image](https://github.com/user-attachments/assets/e6dcb356-6c48-4a31-b5d7-d12414bdb5e2)

**Comment by exoego** [comment]
I thinks this was fixed in [v1.5.4](https://github.com/exoego/esbuild-bundle-analyzer/releases/tag/v1.5.4)
